version: '2'
services:
  acmecategories-app:
    image: acmecategories
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://acmecategories-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=AcmeCategories
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  acmecategories-mongodb:
    extends:
      file: docker-compose.yml
      service: acmecategories-mongodb
